on:
  workflow_call:
    inputs:
      deployment_environment:
        type: string
      product_name:
        type: string

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  deployment:
    environment: ${{ inputs.deployment_environment }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test
        run: |
          echo "test: ${{ vars.ENV_NAME }}"

      - name: filtering mobile configs
        run: |
          echo "$(cat ./build_check_parameters.json | jq '(.isage | .buildParameters[] | select(.Environments | contains(["DEV"])) | .Value)')" > ios_build_config_values.json

      - name: Get build properties
        id: propsFromBuildConfig
        uses: RadovanPelka/github-action-json@main
        with:
          path: "ios_build_config_values.json"

      - name: test
        id: test
        run: |
          cat ios_build_config_values.json
          echo "scheme=${{ toJSON(steps.propsFromBuildConfig.outputs.scheme) }}" >> $GITHUB_OUTPUT

      - name: final test
        run: |
          echo "test: ${{ steps.test.outputs.scheme }}"
