on:
  workflow_call:
    inputs:
      deployment_environment:
        type: string
      product_name:
        type: string

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  deployment:
    environment: ${{ inputs.deployment_environment }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test
        run: |
          echo "test: ${{ vars.ENV_NAME }}"

      - name: filtering mobile configs
        run: |
          echo "$(cat ./test.json | jq '(.| .MOBILE_CONFIG_VALUES | .ISAGE_URLS)')" > ios_build_config_values.json

      - name: prop file json to env variables
        uses: antifree/json-to-variables@v1.2.0
        with:
          filename: test.json

      # - name: test
      #   id: test
      #   run: |
      #     MOBILE_CONFIG_VALUES=$(echo "$(jq '(.| .MOBILE_CONFIG_VALUES | .ISAGE_URLS)' test.json)" | tr -d '\n' | tr -d '\r' )
      #     # echo "MOBILE_CONFIG_VALUES=$MOBILE_CONFIG_VALUES" >> "$GITUB_OUTPUT"

      #     MOBILE_CONFIG_VALUES=$(cat ./ios_build_config_values.json)
      #   echo "name=${MOBILE_CONFIG_VALUES//'%'/'%25'}" >>"$GITHUB_OUTPUTS"

      - name: Substitute env variables in network.json file
        env:
          MOBILE_CONFIG_VALUES: "$(jq '(.| .MOBILE_CONFIG_VALUES | .ISAGE_URLS)' test.json)"
        uses: danielr1996/envsubst-action@1.1.0
        with:
          input: "./network.json"
          output: "./Network-Final.json"

      - name: final test
        run: |
          cat "./Network-Final.json"
