on:
  workflow_call:
    inputs:
      deployment_environment:
        type: string
      product_name:
        type: string

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  deployment:
    environment: ${{ inputs.deployment_environment }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test
        run: |
          echo "test: ${{ vars.ENV_NAME }}"

      - name: cat prop file
        run: |
          echo "file name is : ${{ inputs.product_name }}_build_check_parameters.json"
          cat "${{ inputs.product_name }}_build_check_parameters.json"
