on:
  workflow_call:
    inputs:
      deployment_environment:
        type: string

jobs:
  deployment:
    runs-on: ubuntu-latest

    environment: ${{ inputs.deployment_environment }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test
        run: |
          echo "test: ${{ vars.ENV_NAME }}"
