on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  call-workflow-in-local-repo:
    strategy:
      matrix:
        env_supported:
          [DEV, TEST]
    uses: ./.github/workflows/deploy.yml
    with:
      deployment_environment: ${{ matrix.env_supported }}
