on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - DEV
          - TEST

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  call-workflow-in-local-repo-DEV:
    if: ${{ inputs.environment == 'DEV' }}
    strategy:
      matrix:
        env_supported:
          [DEV, DEVEU]
    uses: ./.github/workflows/deploy.yml
    with:
      deployment_environment: ${{ matrix.env_supported }}
      product_name: "DEV"

  call-workflow-in-local-repo-TEST:
    if: ${{ inputs.environment == 'TEST' }}
    strategy:
      matrix:
        env_supported:
          [TEST, TESTEU]
    uses: ./.github/workflows/deploy.yml
    with:
      deployment_environment: ${{ matrix.env_supported }}
      product_name: "TEST"
