on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/deploy.yml
    with:
      deployment_environment: "DEV"
