on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - DEV
          - TEST
env:
#
  DEV: "['DEVAP-in']"
  TEST: "['DCPRODEU-it','DCPRODEU-fr','DCPRODEU-dk','DCPRODEU-fi','DCPRODEU-ch']"

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  Getting-Countries:
    name:  Getting Countries in ${{ inputs.deployment_region }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - id: set-matrix
        run: echo "matrix=${{ env[format('{0}',inputs.environment)] }}"  >> $GITHUB_OUTPUT
        
  call-workflow-in-local-repo-DEV:
    if: ${{ inputs.environment == 'DEV' }}
    strategy:
      matrix:
        env_supported:
          ${{ fromJson(needs.Getting-Countries.outputs.matrix) }}
    uses: ./.github/workflows/deploy.yml
    with:
      deployment_environment: ${{ matrix.env_supported }}
      product_name: "DEV"

  call-workflow-in-local-repo-TEST:
    if: ${{ inputs.environment == 'TEST' }}
    strategy:
      matrix:
        env_supported:
          ${{ fromJson(needs.Getting-Countries.outputs.matrix) }}
    uses: ./.github/workflows/deploy.yml
    with:
      deployment_environment: ${{ matrix.env_supported }}
      product_name: "TEST"
